### ISSUE TITLE
Video streaming is broken - noticable on edge browser from lumia phone.

### ISSUE THREAD

**Issue by extorn** [yonjah/piwigo-privacy#7]
The content type of the video is not being set - this causes the edge browser (on phones at least) to not successfully parse the videos.

The error is here:

helper_funcs.inc.php
line 76: currently reads `$mime='video/'+$ext;` if I recall correctly
should be
`$mime="video/$ext";`

This sets the mime type to video/mp4 or whatever instead of 0

I'm not an expert, but online examples show the Accept-Ranges header being set to a range of bytes in the file - e.g. `header("Accept-Ranges: 0 -$end");` and not `header("Accept-Ranges: bytes");`. ?Correcting? this header is not necessary for the plugin to function in the edge browser however. If interested, this is on approx line 122 of the same file.

**Comment by yonjah** [comment]
Thanks for noticing the mime bug.
fixed in 0.1.2

As for the ranges example the only valid values is either `bytes` or `none` -
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Ranges
I'm not sure which online examples you saw, but maybe they confused this header with `Content-Range` or if it edge specific maybe it's not following spec
